num_channels: 1024
cpu_offload: False

# model:
#   _target_: anemoi.models.models.AnemoiModelEncProcDec

model:
  _target_: anemoi.models.models.AnemoiModelProc

layer_kernels:
  # The layer_kernels can be adjusted per model component, but are defined here for convenience.
  LayerNorm:
    _target_: torch.nn.LayerNorm
  Linear:
    _target_: torch.nn.Linear
  Activation:
    _target_: torch.nn.GELU
  QueryNorm:
    _target_: anemoi.models.layers.normalization.AutocastLayerNorm
    bias: False
  KeyNorm:
    _target_: anemoi.models.layers.normalization.AutocastLayerNorm
    bias: False

processor:
  _target_: anemoi.models.layers.processor.GraphTransformerProcessor
  trainable_size: ${model.trainable_parameters.hidden2hidden}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_layers: 16
  num_chunks: 2
  mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
  num_heads: 16 # GraphTransformer or Transformer only
  qk_norm: False
  cpu_offload: ${model.cpu_offload}
  layer_kernels: ${model.layer_kernels}

encoder:
  _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
  trainable_size: ${model.trainable_parameters.data2hidden}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_chunks: 1
  mlp_hidden_ratio: 1  # GraphTransformer or Transformer only
  num_heads: 1  # 16 # GraphTransformer or Transformer only
  qk_norm: False
  cpu_offload: ${model.cpu_offload}
  layer_kernels: ${model.layer_kernels}


decoder:
  _target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
  trainable_size: ${model.trainable_parameters.hidden2data}
  sub_graph_edge_attributes: ${model.attributes.edges}
  num_chunks: 1
  mlp_hidden_ratio: 1  # GraphTransformer or Transformer only
  num_heads: 1  # 16 # GraphTransformer or Transformer only   # zero???
  initialise_data_extractor_zero: False
  qk_norm: False
  cpu_offload: ${model.cpu_offload}
  layer_kernels: ${model.layer_kernels}

output_mask:
  _target_: anemoi.training.utils.masks.NoOutputMask

trainable_parameters:
  data: 0  # 8
  hidden: 0  # 8
  data2hidden: 0  # 8
  hidden2data: 0  # 8
  hidden2hidden: 0  # GNN and GraphTransformer Processor only


attributes:
  edges:
  - edge_length
  - edge_dirs
  nodes: []

# Bounding configuration
bounding: #These are applied in order
  - _target_: anemoi.models.layers.bounding.ReluBounding #[0, infinity)
    variables:
    - ro
    - sd
  - _target_: anemoi.models.layers.bounding.NormalizedReluBounding #[0, 1)
    variables:
    - swvl1
    - swvl2
    - swvl3
    min_val:
    - 0
    - 0
    - 0
    normalizer:
    - mean-std
    - mean-std
    - mean-std
  - _target_: anemoi.models.layers.bounding.HardtanhBounding #[0, 1)
    variables:
    # - swvl1
    # - swvl2
    # - swvl3
    - snowc
    min_val: 0
    max_val: 1
  # - _target_: anemoi.models.layers.bounding.FractionBounding # fraction of tp
  #   variables:
  #   - cp
  #   - sf
  #   min_val: 0
  #   max_val: 1
  #   total_var: tp
  # - _target_: anemoi.models.layers.bounding.FractionBounding # fraction of tp
  #   variables:
  #   - lcc
  #   - mcc
  #   - hcc
  #   min_val: 0
  #   max_val: 1
  #   total_var: tcc
  # - _target_: anemoi.models.layers.bounding.LeakyHardtanhBounding #[0, 1)
  #   variables:
  #   - swvl1
  #   - swvl2
  #   min_val: 0
  #   max_val: 0.8
