defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: example
- graph: ailand
- model: graphtransformer
- training: default
- _self_


config_validation: False

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  #plot:
  #  callbacks: []
  log:
    wandb:
      entity: a
    mlflow:
      enabled: False
hardware:
  paths:
    truncation: null
    data: ???
    output: ??
  files:
    truncation: null
    truncation_inv: null
    graph: "debug.pt"
    dataset: ???
model:
  processor:
    _target_: anemoi.models.layers.processor.PointMLP
    num_layers: 4
    num_chunks: 2
    mlp_hidden_ratio: 4
  num_channels: 128
dataloader:
  limit_batches:
    training: 10
    validation: 5
training:
  max_epochs: 2
