overwrite: true

data: data
hidden: hidden

nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
      dataset: /scratch3/NCEPDEV/fv3-cam/Ting.Lei/rrfs-core-subdomain-20km-boundarymask.zarr
    attributes:
      boundary_mask:
        _target_: anemoi.graphs.nodes.attributes.NonzeroAnemoiDatasetVariable
        variable: boundary_mask
      cutout_mask:
        _target_: anemoi.graphs.nodes.attributes.BooleanNot
        masks:
          _target_: anemoi.graphs.nodes.attributes.NonzeroAnemoiDatasetVariable
          variable: boundary_mask
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.MaskedPlanarAreaWeights
        mask_node_attr_name: cutout_mask
        norm: unit-max
  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.LimitedAreaTriNodes
      resolution: 6
      reference_node_name: data
      mask_attr_name: cutout_mask
      margin_radius_km: 20

edges:
  - source_name: data
    target_name: hidden
    edge_builders:
      - _target_: anemoi.graphs.edges.CutOffEdges
        cutoff_factor: 0.6
        source_mask_attr_name: null
        target_mask_attr_name: null
      - _target_: anemoi.graphs.edges.CutOffEdges
        cutoff_factor: 1.5
        source_mask_attr_name: boundary_mask
        target_mask_attr_name: null
    attributes:
      edge_length:
        _target_: anemoi.graphs.edges.attributes.EdgeLength
        norm: unit-std
      edge_dirs:
        _target_: anemoi.graphs.edges.attributes.EdgeDirection
        norm: unit-std
  - source_name: hidden
    target_name: hidden
    edge_builders:
      - _target_: anemoi.graphs.edges.MultiScaleEdges
        x_hops: 1
        scale_resolutions: ${nodes.hidden.node_builder.resolution}
        source_mask_attr_name: null
        target_mask_attr_name: null
    attributes:
      edge_length:
        _target_: anemoi.graphs.edges.attributes.EdgeLength
        norm: unit-std
      edge_dirs:
        _target_: anemoi.graphs.edges.attributes.EdgeDirection
        norm: unit-std
  - source_name: hidden
    target_name: data
    edge_builders:
      - _target_: anemoi.graphs.edges.KNNEdges
        num_nearest_neighbours: 3
        source_mask_attr_name: null
        target_mask_attr_name: cutout_mask
    attributes:
      edge_length:
        _target_: anemoi.graphs.edges.attributes.EdgeLength
        norm: unit-std
      edge_dirs:
        _target_: anemoi.graphs.edges.attributes.EdgeDirection
        norm: unit-std

post_processors:
  - _target_: anemoi.graphs.processors.RemoveUnconnectedNodes
    nodes_name: data
    ignore: cutout_mask
    save_mask_indices_to_attr: indices_connected_nodes
