era5:
  normalizer:
    _target_: anemoi.models.preprocessing.normalizer.InputNormalizer
    config:
      default: "mean-std"
      std:
      - "tp"
      min-max:
      max:
      - "sdor"
      - "slor"
      - "z"
      none:
      - "cos_latitude"
      - "cos_longitude"
      - "sin_latitude"
      - "sin_longitude"
      - "cos_julian_day"
      - "cos_local_time"
      - "sin_julian_day"
      - "sin_local_time"
      - "insolation"
      - "lsm"

cerra:
  normalizer:
    _target_: anemoi.models.preprocessing.normalizer.InputNormalizer
    config:
      default: "mean-std"
      std:
      - "tp"
      min-max:
      max:
      none:
      - "cos_latitude"
      - "cos_longitude"
      - "sin_latitude"
      - "sin_longitude"
      - "cos_julian_day"
      - "cos_local_time"
      - "sin_julian_day"
      - "sin_local_time"
  const_imputer:
    _target_: anemoi.models.preprocessing.imputer.InputImputer
    config:
      default: "mean"
