# @package training.training_loss
datasets:
  data:
    _target_: anemoi.training.losses.MultiscaleLossWrapper
    loss_matrices_path: ${system.input.loss_matrices_path}
    loss_matrices: [null]
    weights: [1.0]

    keep_batch_sharded: ${model.keep_batch_sharded}

    per_scale_loss:
      _target_: anemoi.training.losses.kcrps.AlmostFairKernelCRPS
      scalers: ['pressure_level', 'general_variable', 'nan_mask_weights', 'node_weights', 'time_steps']
      ignore_nans: False
      no_autocast: True
      alpha: 0.95
