asynchronous: True # Whether to plot asynchronously
datashader: True # Choose which technique to use for plotting
frequency: # Frequency of the plotting
  batch: 750
  epoch: 10

# Parameters to plot
parameters:
- z_500
- t_850
- u_850
- v_850
- 2t
- 10u
- 10v
- sp
- tp
- cp

# Sample index
sample_idx: 0

# Precipitation and related fields
precip_and_related_fields: [tp, cp]

# select special colormap for precip fields
colormaps:
  precip:
    _target_: anemoi.training.utils.custom_colormaps.MatplotlibColormapClevels
    clevels: ["#ffffff", "#04e9e7", "#019ff4", "#0300f4", "#02fd02", "#01c501", "#008e00", "#fdf802", "#e5bc00", "#fd9500", "#fd0000", "#d40000", "#bc0000", "#f800fd"]
    variables: ${diagnostics.plot.precip_and_related_fields}

callbacks: []