defaults:
- data: regional
- dataloader: native_grid
- datamodule: multiple
- diagnostics: evaluation
- hardware: example
- graph: regional
- model: regional_graphtransformer
- training: default
- _self_

config_validation: False

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  log:
    wandb:
      entity: None
    mlflow:
      enabled: False
      tracking_uri: None
  plot:
    callbacks: []
hardware:
  files:
    dataset: null
    regional_dataset: cerra-rr-an-oper-0001-mars-5p5km-1984-2020-6h-v2-hmsi
    global_dataset: aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v6
    graph: "debug.pt"
  paths:
    data: None
    output: ${oc.env:HPCPERM}/aifs/refactor/
  accelerator: auto
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1
model:
  num_channels: 128
dataloader:
  limit_batches:
    training: 2
    validation: 2
training:
  model_task: anemoi.training.train.tasks.refactor.ForecastingPLModule
  max_epochs: 2
  training_loss:
    # loss classes to initialise
    regional:
      _target_: anemoi.training.losses.MSELoss
      scalers: []
      ignore_nans: False
