defaults:
- data: downscaling
- dataloader: downscaling
- datamodule: single
- diagnostics: evaluation
- hardware: example
- graph: multi_scale
- model: graphtransformer
- training: downscaling
- _self_

config_validation: False

training:
  model_task: anemoi.training.train.tasks.GraphDownscaler
  max_epochs: 1
  multistep_input: 1

model:
  num_channels: 128

dataloader:
  limit_batches:
    training: 20
    validation: 20
    test: 20

hardware:
  paths:
    truncation: null
    data: /home/mlx/ai-ml/datasets/
    output: ${oc.env:SCRATCH}/anemoi-test/${data.resolution}/
  files:
    truncation: null
    truncation_inv: null
    graph: graph_anemoi_new_${data.resolution}.pt

    # Primary dataset for ERA5
    dataset: aifs-ea-an-oper-0001-mars-${data.resolution}-1979-2023-6h-v8.zarr

    # Secondary dataset for ERA5_copy (using same file for debugging)
    dataset_b: cerra-rr-an-oper-0001-mars-5p5km-1984-2022-6h-v3-hmsi.zarr

  accelerator: auto
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1

data:
  resolution: o96  # Global resolution setting used in hardware file paths
  # Time frequency requested from dataset
  frequency: 6h
  # Time step of model (must be multiple of frequency)
  timestep: 6h

diagnostics:
  plot:
    callbacks: []
  log:
    mlflow:
      enabled: False
      tracking_uri: None
    wandb:
      enabled: False
      entity: example
