defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: example

- graph: encoder_decoder_only
- model: transformer_diffusiontend
# - model: transformer_diffusion

# - graph: multi_scale
# - model: graphtransformer_diffusion
# - model: graphtransformer_diffusiontend

- training: default
- _self_

config_validation: False

diagnostics:
  plot:
    callbacks: []
hardware:
  files:
    graph: ???
  accelerator: auto
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1


model:
  num_channels: 128
  bounding: []

dataloader:
  limit_batches:
    training: 100
    validation: 100

training:
  model_task: anemoi.training.train.forecaster.GraphDiffusionTendForecaster
  # model_task: anemoi.training.train.forecaster.GraphDiffusionForecaster
  max_epochs: 5
