defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: example
- graph: twostep_decoder
- model: graphtransformer
- training: default
- _self_

config_validation: False

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1


diagnostics:
  plot:
    callbacks: []
  log:
    wandb:
      entity: a
    mlflow:
      enabled: False
hardware:
  paths:
    truncation: null
    data: ???
    output: ???
  files:
    truncation: null
    truncation_inv: null
    graph: "debug.pt"
    dataset: aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v6
  accelerator: auto
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1
model:
  num_channels: 128
  model:
    _target_: anemoi.models.models.twostep_decoder.AnemoiModelTwoStepDec
dataloader:
  limit_batches:
    training: 100
    validation: 100
training:
  max_epochs: 5
