defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation_ens
- system: example
- graph: stretched_grid_refiner
- model: graphtransformer_ens_refiner
- training: ensemble
- override /graph/projections/multiscale@_global_.graph.projections.multiscale: 4scale
- _self_

config_validation: False

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# system:
#   hardware:
#     num_gpus_per_node: 2
#     num_gpus_per_model: 2
#     num_gpus_per_ensemble: 2

diagnostics:
  plot:
    parameters:
      - t_500
      - t_850
      - u_500
      - u_850
      - v_500
      - v_850
      - tp

system:
  input:
    # Saved as graph_stretched_refiner_ensemble_n320_data.pt for dataset key "data".
    graph: graph_stretched_refiner_ensemble_n320.pt
    dataset: /home/mlx/ai-ml/datasets/cerra-rr-an-oper-0001-mars-5p5km-1984-2020-6h-v2-hmsi.zarr
    forcing_dataset: /home/mlx/ai-ml/datasets/aifs-ea-an-oper-0001-mars-n320-1979-2023-6h-v8.zarr
    truncation: null
    truncation_inv: null
    loss_matrices_path: null
  output:
    root: ${oc.env:SCRATCH}/aifs-streched
  hardware:
    accelerator: auto
    num_gpus_per_ensemble: 1
    num_gpus_per_node: 4
    num_nodes: 1
    num_gpus_per_model: 1

dataloader:
  dataset:
    cutout:
      - dataset: ${system.input.dataset}
        thinning: 25
      - dataset: ${system.input.forcing_dataset}
    adjust: all
    min_distance_km: 0
  read_group_size: ${system.hardware.num_gpus_per_model}
  # For model sharding (num_gpus_per_model > 1), batch size must stay at 1.
  batch_size:
    training: 1
    validation: 1
    test: 1
  limit_batches:
    training: 100
    validation: 100
  training:
    datasets:
      data:
        dataset_config:
          select:
            - t_500
            - t_850
            - u_500
            - u_850
            - v_500
            - v_850
            - tp
            - lsm
            - cos_latitude
            - cos_longitude
            - sin_latitude
            - sin_longitude
            - cos_julian_day
            - cos_local_time
            - sin_julian_day
            - sin_local_time
        start: 1984
        end: 2018
  validation:
    datasets:
      data:
        dataset_config:
          select:
            - t_500
            - t_850
            - u_500
            - u_850
            - v_500
            - v_850
            - tp
            - lsm
            - cos_latitude
            - cos_longitude
            - sin_latitude
            - sin_longitude
            - cos_julian_day
            - cos_local_time
            - sin_julian_day
            - sin_local_time
        start: 2019
        end: 2019
  test:
    datasets:
      data:
        dataset_config:
          select:
            - t_500
            - t_850
            - u_500
            - u_850
            - v_500
            - v_850
            - tp
            - lsm
            - cos_latitude
            - cos_longitude
            - sin_latitude
            - sin_longitude
            - cos_julian_day
            - cos_local_time
            - sin_julian_day
            - sin_local_time
        start: 2020
        end: null

model:
  num_channels: 128
  attributes:
    edges:
      - edge_length
      - edge_dirs
      - dir_harmonics
      - rbf_features
    nodes: []
  bounding: []

data:
  datasets:
    data:
      forcing:
        - tp
        - lsm
        - cos_latitude
        - cos_longitude
        - sin_latitude
        - sin_longitude
        - cos_julian_day
        - cos_local_time
        - sin_julian_day
        - sin_local_time
      diagnostic: []
      processors:
        normalizer:
          _target_: anemoi.models.preprocessing.normalizer.InputNormalizer
          config:
            default: mean-std
            std:
              - tp
            min-max:
            max:
            none:
              - lsm
              - cos_latitude
              - cos_longitude
              - sin_latitude
              - sin_longitude
              - cos_julian_day
              - cos_local_time
              - sin_julian_day
              - sin_local_time

training:
  lr:
    warmup: 10 # number of warmup iterations
    rate: 0.5e-3
    iterations: ${training.max_steps} # NOTE: When max_epochs < max_steps, scheduler will run for max_steps
    min: 0
  ensemble_size_per_device: 2
  max_epochs: 1
  scalers:
    datasets:
      data:
        node_weights:
          _target_: anemoi.training.losses.scalers.ReweightedGraphNodeAttributeScaler
          nodes_name: ${graph.data}
          nodes_attribute_name: area_weight
          scaling_mask_attribute_name: cutout_mask
          weight_frac_of_total: 0.25
          norm: unit-sum
  training_loss:
    datasets:
      data:
        weights: [1.0, 1.0, 1.0, 1.0, 1.0]
  validation_metrics:
    datasets:
      data:
        multiscale:
          weights: [1.0, 1.0, 1.0, 1.0, 1.0]
  metrics:
    datasets:
      data:
        - t_500
        - t_850
        - u_500
        - u_850
        - v_500
        - v_850

# graph:
#   overwrite: False
