defaults:
- data: zarr_interpolator
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: example
- graph: multi_scale
- model: graphtransformer
- training: interpolator
- _self_

config_validation: True

#dataloader:
  # model_run_info: #Add for non-analysis training
  #  start: 2020-02-05T12:00:00
  #  length: 18 #in number of dates (* frequency for actual time)

model:
  model:
    _target_: anemoi.models.models.AnemoiModelEncProcDecInterpolator
  latent_skip: True # True/False for skip connection on latent mesh
  grid_skip: 0 # Which of the input indices to use as residual connection, null if none.



  # Mass-conserving accumulations
  # Ensure each predicted interpolated target sums to its accumulated forcing input.
  # The sum of predicted targets at `training.explicit_times.target` (with step `data.frequency`)
  #   should match the accumulated input at `training.explicit_times.input[-1]` e.g. the r.h.s of the accumulation input
  # Requirements:
  # - In config.data: targets must be listed under `diagnostic`; accumulation inputs under `forcing`.
  # - Use the `zero_overwriter` processor to zero the left boundary (time_indices=0) of each accumulation input,
  mass_conserving_accumulations: # target : constraint
    tp : tp_accum
    cp : cp_accum

training:

  explicit_times:
    input: [0,6]
    target: [1,2,3,4,5]

  target_forcing: #forcing parameters for the target time to include as input
    data: #of which come from the dataset
      - "insolation"
    time_fraction: True

diagnostics:
  log:
    mlflow:
      max_params_length: 3000

  plot: # Callbacks are currently not supported for interpolator
    callbacks: []
    colormaps: {}
