defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: multi_scale
- model: graphtransformer
- task: temporal_downscaling
- training: single
- _self_

config_validation: True
