defaults:
- data: zarr_ex_accum
- dataloader: native_grid_ex_accum
- datamodule: single
- diagnostics: evaluation
- hardware: example
- graph: multi_scale
- model: transformer
- training: interpolator
- _self_

config_validation: True

hardware:
  files:
    dataset: aifs-ea-an-oper-0001-mars-o96-1979-2022-1h-v4.zarr

data:
  frequency: 1h
  timestep: 1h
  resolution: o96

  diagnostics: [] # Default behaviour is to interpolate between observed fields, not predict unseen fields

#dataloader:
  # model_run_info: #Add for non-analysis training
  #  start: 2020-02-05T12:00:00
  #  length: 18 #in number of dates (* frequency for actual time)

model:
  model:
    _target_: anemoi.models.models.interpolator.AnemoiModelEncProcDecInterpolator
  latent_skip: False # True/False for skip connection on latent mesh
  grid_skip: 0 # Which of the input indices to use as residual connection, null if none.

  # Bounding configuration
  bounding: #These are applied in order

    # Bound tp (total precipitation) with a Relu bounding layer
    # ensuring a range of [0, infinity) to avoid negative precipitation values.
    - _target_: anemoi.models.layers.bounding.ReluBounding #[0, infinity)
      variables:
      - tp

    - _target_: anemoi.models.layers.bounding.FractionBounding # fraction of tp
      variables:
      - cp
      min_val: 0
      max_val: 1
      total_var: tp


training:
  # Instead of inferred using multistep and timeincrement, specify time indices explicitly
  explicit_times:
    input: [0,6]
    target: [1,2,3,4,5]

  target_forcing: #forcing parameters for the target time to include as input
    data: #of which come from the dataset
      - "insolation"
    time_fraction: True
