defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- hardware: slurm
- graph: multi_scale
- model: graphtransformer
- training: default
- _self_

no_validation: False

data:
  frequency: 1h

#dataloader:
  # model_run_info: #Add for non-analysis training
  #  start: 2020-02-05T12:00:00
  #  length: 18 #in number of dates (* frequency for actual time)

model:
  model:
    _target_: anemoi.models.models.AnemoiModelEncProcDecInterpolator
    latent_skip: False # True/False for skip connection on latent mesh
    grid_skip: 0 # Which of the input indices to use as residual connection, null if none.

training:
  train_module: anemoi.training.train.interpolator
  train_function: GraphInterpolator

  explicit_times:
    input: [0,6]
    target: [1,2,3,4,5]

  target_forcing: #forcing parameters for the target time to include as input
    data: #of which come from the dataset
      - "insolation"
    custom: #custom forcings calculated on the fly
      - "time_frac" #fraction of time at target with respect to the initial and final truth times
      #TODO: make this optional or remove option, currently hardcoded.
