defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: stretched_grid
- model: graphtransformer
- task: forecaster
- training: stretched
- reset@_global_: multidomain
- _self_

config_validation: True

system:
  input:
    dataset: ???
    forcing_dataset: ???

diagnostics:
  plot:
    datasets_to_plot: [sg_1, sg_2]

dataloader:
  strategy:
    _target_: anemoi.training.data.multidomain.MultiDomainDataset
  batch_size:
    training: 1
    validation: 1
    test: 1
  training:
    datasets:
      sg_1:
        dataset_config:
          dataset:
            cutout:
            - dataset: ${system.input.dataset}
              area: [70, -10, 55, 30]
              thinning: 25
            - dataset: ${system.input.forcing_dataset}
            adjust: all
            min_distance_km: 0
          frequency: ${data.frequency}
        start: null
        end: 2020
      sg_2:
        dataset_config:
          dataset:
            cutout:
            - dataset: ${system.input.dataset}
              area: [72, -25, 52, 50]
              thinning: 25
            - dataset: ${system.input.forcing_dataset}
            adjust: all
            min_distance_km: 0
          frequency: ${data.frequency}
        start: ${dataloader.training.datasets.sg_1.start}
        end: ${dataloader.training.datasets.sg_1.end}
  validation:
    datasets:
      sg_1:
        dataset_config: ${dataloader.training.datasets.sg_1.dataset_config}
        start: 2021
        end: 2021
      sg_2:
        dataset_config: ${dataloader.training.datasets.sg_2.dataset_config}
        start: ${dataloader.validation.datasets.sg_1.start}
        end: ${dataloader.validation.datasets.sg_1.end}
  test:
    datasets:
      sg_1:
        dataset_config: ${dataloader.training.datasets.sg_1.dataset_config}
        start: 2022
        end: null
      sg_2:
        dataset_config: ${dataloader.training.datasets.sg_2.dataset_config}
        start: ${dataloader.test.datasets.sg_1.start}
        end: ${dataloader.test.datasets.sg_1.end}

data:
  datasets:
    sg_1:
      forcing:
      - cos_latitude
      - cos_longitude
      - sin_latitude
      - sin_longitude
      - cos_julian_day
      - cos_local_time
      - sin_julian_day
      - sin_local_time
      - insolation
      - lsm
      - sdor
      - slor
      - z
      diagnostic: [tp, cp]
      processors:
        normalizer:
          _target_: anemoi.models.preprocessing.normalizer.InputNormalizer
          config:
            default: mean-std
            std: [tp]
            min-max:
            max: [sdor, slor, z]
            none:
            - cos_latitude
            - cos_longitude
            - sin_latitude
            - sin_longitude
            - cos_julian_day
            - cos_local_time
            - sin_julian_day
            - sin_local_time
            - insolation
            - lsm
    sg_2: ${data.datasets.sg_1}

graph:
  # Each domain has its own data nodes, hidden mesh, and graph edges.
  nodes:
    sg_1:
      node_builder:
        _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
        dataset: ${dataloader.training.datasets.sg_1.dataset_config}
      attributes: ${graph.attributes.nodes}
    sg_1_hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.StretchedTriNodes
        lam_resolution: 8
        global_resolution: 5
        reference_node_name: sg_1
        mask_attr_name: cutout_mask
        margin_radius_km: 11
    sg_2:
      node_builder:
        _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
        dataset: ${dataloader.training.datasets.sg_2.dataset_config}
      attributes: ${graph.attributes.nodes}
    sg_2_hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.StretchedTriNodes
        lam_resolution: ${graph.nodes.sg_1_hidden.node_builder.lam_resolution}
        global_resolution: ${graph.nodes.sg_1_hidden.node_builder.global_resolution}
        reference_node_name: sg_2
        mask_attr_name: cutout_mask
        margin_radius_km: 11
  edges:
  - source_name: sg_1
    target_name: sg_1_hidden
    edge_builders:
    - _target_: anemoi.graphs.edges.KNNEdges
      num_nearest_neighbours: 12
      source_mask_attr_name: null
      target_mask_attr_name: null
    attributes: ${graph.attributes.edges}
  - source_name: sg_1_hidden
    target_name: sg_1_hidden
    edge_builders:
    - _target_: anemoi.graphs.edges.MultiScaleEdges
      x_hops: 1
      scale_resolutions: ${graph.nodes.sg_1_hidden.node_builder.lam_resolution}
      source_mask_attr_name: null
      target_mask_attr_name: null
    attributes: ${graph.attributes.edges}
  - source_name: sg_1_hidden
    target_name: sg_1
    edge_builders:
    - _target_: anemoi.graphs.edges.KNNEdges
      num_nearest_neighbours: 3
      source_mask_attr_name: null
      target_mask_attr_name: null
    attributes: ${graph.attributes.edges}
  - source_name: sg_2
    target_name: sg_2_hidden
    edge_builders:
    - _target_: anemoi.graphs.edges.KNNEdges
      num_nearest_neighbours: 12
      source_mask_attr_name: null
      target_mask_attr_name: null
    attributes: ${graph.attributes.edges}
  - source_name: sg_2_hidden
    target_name: sg_2_hidden
    edge_builders:
    - _target_: anemoi.graphs.edges.MultiScaleEdges
      x_hops: 1
      scale_resolutions: ${graph.nodes.sg_2_hidden.node_builder.lam_resolution}
      source_mask_attr_name: null
      target_mask_attr_name: null
    attributes: ${graph.attributes.edges}
  - source_name: sg_2_hidden
    target_name: sg_2
    edge_builders:
    - _target_: anemoi.graphs.edges.KNNEdges
      num_nearest_neighbours: 3
      source_mask_attr_name: null
      target_mask_attr_name: null
    attributes: ${graph.attributes.edges}

model:
  model:
    hidden_nodes_name:
      sg_1: sg_1_hidden
      sg_2: sg_2_hidden
  # Both domains use the same encoder and decoder weights.
  encoders:
    "0":
      source_datasets: [sg_1, sg_2]
  decoders:
    "0":
      target_datasets: [sg_1, sg_2]
  node_trainable_parameters:
    sg_1: 0
    sg_1_hidden: 0
    sg_2: 0
    sg_2_hidden: 0
  edge_trainable_parameters:
    data2hidden: 0
    hidden2hidden: 0
    hidden2data: 0
  residual:
    datasets:
      sg_1:
        _target_: anemoi.models.layers.residual.SkipConnection
        step: -1
      sg_2: ${model.residual.datasets.sg_1}
  output_mask:
    datasets:
      sg_1:
        _target_: anemoi.training.utils.masks.NoOutputMask
      sg_2: ${model.output_mask.datasets.sg_1}
  bounding:
    datasets:
      sg_1:
      - _target_: anemoi.models.layers.bounding.ReluBounding
        variables: [tp]
      sg_2: ${model.bounding.datasets.sg_1}

training:
  scalers:
    datasets:
      sg_1:
        general_variable:
          _target_: anemoi.training.losses.scalers.GeneralVariableLossScaler
          weights:
            default: 1
            q: 0.6
            t: 6
            u: 0.8
            v: 0.5
            w: 0.001
            z: 12
            sp: 10
            10u: 0.1
            10v: 0.1
            2d: 0.5
            tp: 0.025
            cp: 0.0025
        pressure_level:
          _target_: anemoi.training.losses.scalers.ReluVariableLevelScaler
          group: pl
          y_intercept: 0.2
          slope: 0.001
        nan_mask_weights:
          _target_: anemoi.training.losses.scalers.NaNMaskScaler
        stdev_tendency:
          _target_: anemoi.training.losses.scalers.StdevTendencyScaler
        var_tendency:
          _target_: anemoi.training.losses.scalers.VarTendencyScaler
        node_weights:
          _target_: anemoi.training.losses.scalers.ReweightedGraphNodeAttributeScaler
          nodes_attribute_name: area_weight
          scaling_mask_attribute_name: cutout_mask
          weight_frac_of_total: 0.25
          norm: unit-sum
        lam_node_weights:
          _target_: anemoi.training.losses.scalers.GraphNodeAttributeScaler
          nodes_attribute_name: lam_area_weight
          norm: unit-sum
        limited_area_mask:
          _target_: anemoi.training.losses.scalers.GraphNodeAttributeScaler
          nodes_attribute_name: cutout_mask
          norm: null
        outside_lam_mask:
          _target_: anemoi.training.losses.scalers.GraphNodeAttributeScaler
          nodes_attribute_name: boundary_mask
          norm: null
        time_steps:
          _target_: anemoi.training.losses.scalers.UniformTimeStepScaler
      sg_2: ${training.scalers.datasets.sg_1}
  training_loss:
    datasets:
      sg_1:
        _target_: anemoi.training.losses.MSELoss
        scalers: [pressure_level, general_variable, node_weights, time_steps]
        ignore_nans: false
      sg_2: ${training.training_loss.datasets.sg_1}
  validation_metrics:
    datasets:
      sg_1:
        mse:
          _target_: anemoi.training.losses.MSELoss
          scalers: [node_weights, time_steps]
          ignore_nans: true
        mse_inside_lam_contribution:
          _target_: anemoi.training.losses.MSELoss
          scalers: [limited_area_mask, node_weights, time_steps]
          ignore_nans: true
        mse_outside_lam_contribution:
          _target_: anemoi.training.losses.MSELoss
          scalers: [outside_lam_mask, node_weights, time_steps]
          ignore_nans: true
        mse_inside_lam:
          _target_: anemoi.training.losses.MSELoss
          scalers: [lam_node_weights, time_steps]
          ignore_nans: true
      sg_2: ${training.validation_metrics.datasets.sg_1}
  variable_groups:
    datasets:
      sg_1:
        default: sfc
        pl:
          param: [q, t, u, v, w, z]
      sg_2: ${training.variable_groups.datasets.sg_1}
  metrics:
    datasets:
      sg_1: [z_500, t_850, u_850, v_850]
      sg_2: ${training.metrics.datasets.sg_1}
