defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: multi_scale
- model_builder: direct
- model: naive
- training: default
- _self_

config_validation: True
