defaults:
- data: zarr
- dataloader: native_grid
- datamodule: single
- diagnostics: evaluation
- hardware: example
- graph: existing_graph
- model: graphtransformer
- training: stretched
- _self_

config_validation: True

diagnostics:
  profiler: False
  benchmark_profiler:
    memory:
      enabled: true
      steps: 5
      warmup: 2
      extra_plots: true
      trace_rank0_only: false
    time:
      enabled: true
      verbose: false
    speed:
      enabled: true
    system:
      enabled: true
    model_summary:
      enabled: false
    snapshot:
      enabled: true
      steps: 4
      warmup: 0
  print_memory_summary: True
  plot:
    callbacks: []
    parameters:
      - z_500
      - t_850
      - u_850
      - v_850
      - 2t
      - 10u
      - 10v
      - sp
      - tp
    precip_and_related_fields: [tp]
  log:
    mlflow:
      enabled: True
      offline: True
      experiment_name: 'aromeia-lumi-debug'
      project_name: 'aromeia'
      run_name: 'testing-lumi'
      tracking_uri: 'https://mlflow.ecmwf.int'
      authentication: True
      terminal: False
      system: True
    wandb:
      enabled: False
      entity: 'aromeia'

data:
  forcing:
    - "cos_latitude"
    - "cos_longitude"
    - "sin_latitude"
    - "sin_longitude"
    - "cos_julian_day"
    - "cos_local_time"
    - "sin_julian_day"
    - "sin_local_time"
    - "insolation"
    - "lsm"
    - "z"
  diagnostic: ["tp"]
  normalizer:
    max: ["z"]

dataloader:
  num_workers:
    training: 8
    validation: 8
  batch_size:
    training: 1
    validation: 1
  validation:
      start: "2023-06-01"
      end: "2023-06-20"
  test:
      start: "2023-06-21"
      end: "2023-07-11"
  dataset:
    cutout:
      - dataset: ${hardware.paths.data}/${hardware.files.titan_dataset}
        select: ['10u', '10v', '2d', '2t', 'msl', 'sp', 'skt', 'z', 'tp', 'q_50', 'q_100', 'q_150', 'q_200', 'q_250', 'q_300', 'q_400', 'q_500', 'q_700', 'q_850', 'q_925', 'q_1000', 't_50', 't_100', 't_150', 't_200', 't_250', 't_300', 't_400', 't_500', 't_700', 't_850', 't_925', 't_1000', 'u_50', 'u_100', 'u_150', 'u_200', 'u_250', 'u_300', 'u_400', 'u_500', 'u_700', 'u_850', 'u_925', 'u_1000', 'v_50', 'v_100', 'v_150', 'v_200', 'v_250', 'v_300', 'v_400', 'v_500', 'v_700', 'v_850', 'v_925', 'v_1000', 'z_50', 'z_100', 'z_150', 'z_200', 'z_250', 'z_300', 'z_400', 'z_500', 'z_700', 'z_850', 'z_925', 'z_1000', lsm, insolation, cos_julian_day, cos_latitude, cos_local_time, cos_longitude, sin_julian_day, sin_latitude, sin_local_time, sin_longitude]
        rescale:
          tp:
            scale: 0.001
            offset: 0.0
      - dataset: ${hardware.paths.data}/${hardware.files.forcing_dataset}
        select: ['10u', '10v', '2d', '2t', 'msl', 'sp', 'skt', 'z', 'tp', 'q_50', 'q_100', 'q_150', 'q_200', 'q_250', 'q_300', 'q_400', 'q_500', 'q_700', 'q_850', 'q_925', 'q_1000', 't_50', 't_100', 't_150', 't_200', 't_250', 't_300', 't_400', 't_500', 't_700', 't_850', 't_925', 't_1000', 'u_50', 'u_100', 'u_150', 'u_200', 'u_250', 'u_300', 'u_400', 'u_500', 'u_700', 'u_850', 'u_925', 'u_1000', 'v_50', 'v_100', 'v_150', 'v_200', 'v_250', 'v_300', 'v_400', 'v_500', 'v_700', 'v_850', 'v_925', 'v_1000', 'z_50', 'z_100', 'z_150', 'z_200', 'z_250', 'z_300', 'z_400', 'z_500', 'z_700', 'z_850', 'z_925', 'z_1000', lsm, insolation, cos_julian_day, cos_latitude, cos_local_time, cos_longitude, sin_julian_day, sin_latitude, sin_local_time, sin_longitude]
    adjust: all
    min_distance_km: 0

model:
  trainable_parameters:
    data: 0
    data2hidden: 0
    hidden: 0
    hidden2data: 0
    hidden2hidden: 0
  processor:
    num_chunks: 2

training:
  load_weights_only: True
  transfer_learning: True
  fork_run_id: starting-point
  scalers:
    node_weights:
      weight_frac_of_total: 0.33

hardware:
  paths:
    data: /project/home/p200177/DE_371/datasets/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6
    output: /home/users/u102751/code/anemoi/anemoi-mf/recipes/4-unconddiff-dev/training/outputs/
  files:
    dataset: arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6.zarr
    graph: /home/users/u102751/code/anemoi/anemoi-mf/recipes/4-unconddiff-dev/graphs/graph_AROME_full.pt
  num_gpus_per_node: 4
  num_gpus_per_model: 2
