defaults:
  - data: zarr
  - dataloader: rrfs_native_no_frequency
  - diagnostics: evaluation_no_plot
  - system: example
  - graph: existing_graph
  - model: graphtransformer
  - training: lam
  - _self_

config_validation: True

data:
  resolution: 3p0km
  frequency: 1h
  timestep: 1h
  forcing: []
  diagnostic: []
  normalizer:
    default: "mean-std"
    std: []
    min-max: []
    max: []
    none:
      - icmr_850
      - icmr_925
      - snmr_850
      - snmr_925
      - refc

system:
  hardware:
    num_gpus_per_node: 1
    num_nodes: 1
    num_gpus_per_model: 1
  input:
    dataset: /scratch3/NCEPDEV/fv3-cam/Ting.Lei/dr-anemoi-core/anemoi-core/test-20km-bcmask-time.zarr
    graph: /scratch3/NCEPDEV/fv3-cam/Ting.Lei/tlei-anemoi-training/graphs/rrfs-3km-lam-graph-20km.pt
  output:
    root: /scratch3/NCEPDEV/fv3-cam/Ting.Lei/tlei-anemoi-training/

dataloader:
  batch_size:
    training: 1
    validation: 1
    test: 1
  num_workers:
    training: 4
    validation: 4
    test: 4
  training:
    start: "2024-05-05T00:00:00"
    end: "2024-05-05T17:00:00"
    drop: [boundary_mask]
  validation:
    start: "2024-05-05T18:00:00"
    end: "2024-05-05T20:00:00"
    drop: [boundary_mask]
  test:
    start: "2024-05-05T21:00:00"
    end: "2024-05-05T23:00:00"
    drop: [boundary_mask]

training:
  metrics:
    - height_500
    - temp_850
    - ugrd_850
    - vgrd_850
  variable_groups:
    default: sfc
    pl:
      is_pressure_level: True
