defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: multi_scale
- model: graphtransformer
- task: temporal_downscaler
- training: single
- override training/losses: combined
- _self_

config_validation: True

diagnostics:
  plot:
    callbacks: []
  callbacks: []
