defaults:
- data: multi_debug
- dataloader: multi_dataset
- datamodule: multi
- diagnostics: evaluation
- hardware: example
- graph: multi_scale
- model: graphtransformer
- training: multi_debug
- _self_

config_validation: False

training:
  # select model
  model_task: anemoi.training.train.tasks.GraphMultiDatasetForecaster

model:
  num_channels: 128


hardware:
  files:
    graph: graph_anemoi_new_${data.resolution}.pt

    # Primary dataset for ERA5
    dataset: aifs-ea-an-oper-0001-mars-${data.resolution}-1979-2023-6h-v8.zarr

    # Secondary dataset for ERA5_copy (using same file for debugging)
    dataset_b: aifs-ea-an-oper-0001-mars-${data.resolution}-1979-2023-6h-v8.zarr

  accelerator: auto
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1


data:
  resolution: o96  #  not used anymore ...
  # Time frequency requested from dataset
  frequency: 6h
  # # Time step of model (must be multiple of frequency)
  timestep: 6h
