defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- system: example
- graph: multi_scale
- model: graphtransformer_diffusiontend
- task: forecaster
- training: stochastic_interpolant
- _self_


config_validation: True

model:
  model:
    transport:
      objective: stochastic_interpolant
      source:
        kind: zero

training:
  prediction_mode: tendency
