_target_: anemoi.models.layers.mapper.GNNBackwardMapper
trainable_size: ${model.trainable_parameters.hidden2data}
sub_graph_edge_attributes: ${model.attributes.edges}
num_chunks: 1
mlp_extra_layers: 0
cpu_offload: ${model.cpu_offload}
gradient_checkpointing: True
layer_kernels: ${model.layer_kernels}
