_target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
trainable_size: ${model.trainable_parameters.hidden2data}
sub_graph_edge_attributes: ${model.attributes.edges}
num_chunks: 4
mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
num_heads: 16 # GraphTransformer or Transformer only
initialise_data_extractor_zero: False
qk_norm: False
cpu_offload: ${model.cpu_offload}
gradient_checkpointing: True
layer_kernels: ${model.layer_kernels}
shard_strategy: "edges"
graph_attention_backend: "triton"  # Options: "triton", "pyg"
edge_pre_mlp: False
