_target_: anemoi.models.layers.mapper.TransformerBackwardMapper
_convert_: all
cpu_offload: ${model.cpu_offload}
gradient_checkpointing: True
num_chunks: 2
mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
num_heads: 16 # GraphTransformer or Transformer only
window_size: -1
dropout_p: 0.0
attention_implementation: flash_attention # Possible values: scaled_dot_product_attention, flash_attention
softcap: 0.0 # Transformer only
use_alibi_slopes: False # Transformer only
qk_norm: False
use_rotary_embeddings: False
layer_kernels: ${model.layer_kernels}
shard_strategy: "edges"
