defaults:
- data: zarr_interp
- dataloader: native_grid
- diagnostics: evaluation
- datamodule: ens
- hardware: slurm
- graph: n320
- model: graphtransformer_ens
- training: ensemble
- override hydra/hydra_logging: disabled
- override hydra/job_logging: disabled
- _self_

config_validation: False

hydra:
  output_subdir: null
  run:
    dir: .

data:
  frequency: 1h
  timestep: 1h

dataloader:
  num_workers:
    training: 8 #4
    validation: 4
    test: 4
  batch_size:
    training: 1
    validation: 1
    test: 1
  limit_batches:
    training: 2000 #5000 #null
    validation: 100 #10 #0 #null
  training:
    start: 1979-01-01
    end: 2022-05-31
    drop: [sdor, slor, q_10, u_10, v_10, w_10, t_10, z_10]
  validation:
    start: 2022-06-01
    end: 2023-05-31
    drop: [sdor, slor, q_10, u_10, v_10, w_10, t_10, z_10]
  test:
    start: 2022-06-01
    end: 2023-05-31
  prefetch_factor: 2
  validation_rollout: 1

diagnostics:
  log:
    interval: 100
    wandb:
      entity: null
    mlflow:
      enabled: True #True #True
      offline: True #True
      authentication: True
      experiment_name: metno
      tracking_uri: https://mlflow.ecmwf.int
      run_name: interpolator
      system: True

hardware:
  files:
    dataset: aifs-ea-an-oper-0001-mars-n320-1979-2024-1h-v2-with-era51.zarr
    graph: graph_interp_n320.pt
  num_gpus_per_ensemble: 2 #4
  num_gpus_per_model: 1 #4

model:
  num_channels: 1024
  keep_batch_sharded: False
  bounding:
    - _target_: anemoi.models.layers.bounding.ReluBounding #[0, infinity)
      variables:
        - tp
    - _target_: anemoi.models.layers.bounding.HardtanhBounding #[min_val, max_val]
      variables:
        - tcc
        - hcc
        - mcc
        - lcc
      min_val: 0
      max_val: 1
  trainable_parameters:
    data: 0
    hidden: 0
    data2hidden: 0
    hidden2data: 0
    hidden2hidden: 0
  processor:
   num_chunks: 8
  encoder:
   num_chunks: 8
  model:
    _target_: anemoi.models.models.AnemoiModelEncProcDecEnsInterpMulti
  latent_skip: False
  grid_skip: 1 # Which of the input indices to use as residual connection, null if none.

training:
  scalers:
    general_variable:
      _target_: anemoi.training.losses.scalers.GeneralVariableLossScaler
      weights:
        default: 1
        q: 1
        t: 1   #1
        u: 1 #0.5
        v: 1 #0.33
        w: 0.1
        z: 1  #1
        sp: 1
        msl: 1
        10u: 1
        10v: 1
        2d: 1
        tp: 0.025
        cp: 0.0025
  multistep_input: 1
  model_task: anemoi.training.train.tasks.GraphEnsInterpMulti
  explicit_times:
    input: [0,6]
    target: [1,2,3,4,5,6]
  aggregate_outputs: #calculate loss on time-aggregated outputs
    - mean
    - max
    - min
    - diff
  use_all_targets: False #whether to use all interp targets or pick a random one.
  #Used with 30 data parallel and 2 ens members. Per target effective batch size of only 6, but 30 with a$

  run_id: null
  ensemble_size_per_device: 1
  max_epochs: null
  max_steps: 200000
  #load_weights_only: True
  #transfer_learning: True
  lr:
    rate: 5.0e-5
    min: 3e-7
    warmup: 1000
  training_loss:
    _target_: anemoi.training.losses.AlmostFairKernelCRPS #non-combined loss
    alpha: 0.95
    scalers: ['pressure_level', 'general_variable', 'nan_mask_weights', 'node_weights', 'stdev_tendency']
    ignore_nans: False

  rollout:
    start: 1
    epoch_increment: 0
    max: 1

graph:
  overwrite: False
