defaults:
- data: zarr_interp
- dataloader: native_grid_forecaster
- diagnostics: evaluation
- datamodule: ens
- hardware: slurm
- graph: n320
- model: graphtransformer_ens_new
- training: ensemble_new
- override hydra/hydra_logging: disabled
- override hydra/job_logging: disabled
- _self_

config_validation: False

hydra:
  output_subdir: null
  run:
    dir: .

data:
  frequency: 1h
  timestep: 1h

dataloader:
  limit_batches:
    training: 2000 #5000 #null
    validation: 100 #10 #0 #null

diagnostics:
  log:
    interval: 100
    wandb:
      entity: null
    mlflow:
      enabled: True #True #True
      offline: True #True
      authentication: True
      experiment_name: metno
      tracking_uri: https://mlflow.ecmwf.int
      run_name: interpolator
      system: True

hardware:
  loss_matrices_path: /e/home/jusers/clare1/jupiter/
  files:
    dataset: aifs-od-fc-oper-0001-mars-n320-2016-2024-1h-v1.zarr
    graph: graph_interp_n320.pt
  num_gpus_per_ensemble: 2 #4
  num_gpus_per_model: 1 #4

model:
  noise_injector:
    _target_: anemoi.models.layers.ensemble_new.NoiseConditioning
    noise_std: 1
    noise_channels_dim: 4
    noise_mlp_hidden_dim: 32
    noise_matrix: /e/home/jusers/clare1/jupiter/gaussian_filter_noise_o32_o96_cutoff.npz
    row_normalize_noise_matrix: false
    autocast: false
    layer_kernels:
      Activation:
        _target_: torch.nn.GELU
  model_run_info: #Add for non-analysis training
    start: 2016-01-01T00:00:00
    length: 18 #in number of dates (* frequency for actual time)
  num_channels: 1024
  keep_batch_sharded: False
  bounding:
    - _target_: anemoi.models.layers.bounding.ReluBounding #[0, infinity)
      variables:
        - tp
    - _target_: anemoi.models.layers.bounding.HardtanhBounding #[min_val, max_val]
      variables:
        - tcc
        - hcc
        - mcc
        - lcc
      min_val: 0
      max_val: 1
  trainable_parameters:
    data: 0
    hidden: 0
    data2hidden: 0
    hidden2data: 0
    hidden2hidden: 0
  processor:
   num_chunks: 8
  encoder:
   num_chunks: 8
  decoder:
   num_chunks: 8

  model:
    _target_: anemoi.models.models.AnemoiModelEncProcDecEnsInterpMulti
  latent_skip: False
  grid_skip: 1 # Which of the input indices to use as residual connection, null if none.

training:
  load_weights_only: True
  transfer_learning: True
  scalers:
    general_variable:
      _target_: anemoi.training.losses.scalers.GeneralVariableLossScaler
      weights:
        default: 1
        q: 1
        t: 1   #1
        u: 1 #0.5
        v: 1 #0.33
        w: 0.1
        z: 1  #1
        sp: 1
        msl: 1
        10u: 1
        10v: 1
        2d: 1
        tp: 0.025
        cp: 0.0025
  multistep_input: 1
  model_task: anemoi.training.train.tasks.GraphEnsInterpMulti
  explicit_times:
    input: [0,6]
    target: [1,2,3,4,5,6]
  aggregate_outputs: #calculate loss on time-aggregated outputs
    - mean
    - max
    - min
    - diff
  use_all_targets: False #whether to use all interp targets or pick a random one.
  #Used with 30 data parallel and 2 ens members. Per target effective batch size of only 6, but 30 with all targets.
  run_id: null
  ensemble_size_per_device: 1
  max_epochs: null
  max_steps: 200000
  #load_weights_only: True
  #transfer_learning: True
  lr:
    rate: 5.0e-5
    min: 3e-7
    warmup: 1000
    iterations: 200000
  training_loss:
    _target_: anemoi.training.losses.MultiscaleLossWrapper
    loss_matrices_path: ${hardware.loss_matrices_path}
    loss_matrices:
    - filter_n320_w=gaussian_d=8.0x.npz
    - filter_n320_w=gaussian_d=2.0x.npz
    - null
    weights:
    - 1.0
    - 2.0
    - 4.0
    keep_batch_sharded: ${model.keep_batch_sharded}
    per_scale_loss:
      _target_: anemoi.training.losses.kcrps_new.AlmostFairKernelCRPS
      scalers:
      - pressure_level
      - general_variable
      - nan_mask_weights
      - node_weights
      - stdev_tendency
      no_autocast: true
      ignore_nans: false
      alpha: 0.95
  validation_metrics:
    afkcrps:
      _target_: anemoi.training.losses.kcrps_new.AlmostFairKernelCRPS
      scalers:
      - node_weights
      ignore_nans: false
      alpha: 1.0
  rollout:
    start: 1
    epoch_increment: 0
    max: 1

graph:
  overwrite: False
