defaults:
  - /processors@processors: default

_target_: anemoi.models.builder.build_anemoi_model
_recursive_: false

multistep_input: ${training.multistep_input}
multistep_output: ${training.multistep_output}

keep_batch_sharded: True

backbone:
  _target_: anemoi.models.models.AnemoiEnsModelEncProcDec
  data_nodes_name: "data"
  hidden_nodes_name: "hidden"
  latent_skip: True

  num_channels: 1024
  cpu_offload: False
  condition_on_residual: False

  noise_injector:
    _target_: anemoi.models.layers.ensemble.NoiseConditioning
    noise_std: 1
    noise_channels_dim: 4
    noise_mlp_hidden_dim: 32
    noise_matrix: null
    row_normalize_noise_matrix: false
    autocast: false
    layer_kernels:
      Activation:
        _target_: torch.nn.GELU

  layer_kernels:
    # The layer_kernels can be adjusted per model component, but are defined here for convenience.
    LayerNorm:
      _target_: torch.nn.LayerNorm
    Linear:
      _target_: torch.nn.Linear
    Activation:
      _target_: torch.nn.GELU
    QueryNorm:
      _target_: anemoi.models.layers.normalization.AutocastLayerNorm
      bias: False
    KeyNorm:
      _target_: anemoi.models.layers.normalization.AutocastLayerNorm
      bias: False

  processor:
    _target_: anemoi.models.layers.processor.TransformerProcessor
    num_layers: 16
    num_chunks: 2
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 16 # GraphTransformer or Transformer only
    window_size: 512
    dropout_p: 0.0
    attention_implementation: flash_attention # Possible values:  scaled_dot_product_attention, flash_attention
    qk_norm: True # Transformer and GraphTransformer only
    softcap: 0.0 # Transformer only
    use_alibi_slopes: False # Transformer only
    cpu_offload: ${model.backbone.cpu_offload}
    gradient_checkpointing: True
    layer_kernels:
      LayerNorm:
        _target_: anemoi.models.layers.normalization.ConditionalLayerNorm
        normalized_shape: ${model.backbone.num_channels}
        condition_shape: ${model.backbone.noise_injector.noise_channels_dim}
        zero_init: True
        autocast: false
        #Any arguments to your chosen function go here
      Linear:
        _target_: torch.nn.Linear # These reflect the defaults, but are shown here for clarity
      Activation:
        _target_: torch.nn.GELU

  encoder:
    _target_: anemoi.models.layers.mapper.GraphTransformerForwardMapper
    trainable_size: ${model.backbone.trainable_parameters.data2hidden}
    sub_graph_edge_attributes: ${model.backbone.attributes.edges}
    num_chunks: 4
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 16 # GraphTransformer or Transformer only
    qk_norm: False
    cpu_offload: ${model.backbone.cpu_offload}
    gradient_checkpointing: True
    layer_kernels: ${model.backbone.layer_kernels}
    shard_strategy: "edges"
    graph_attention_backend: "triton"  # Options: "triton", "pyg"

  decoder:
    _target_: anemoi.models.layers.mapper.GraphTransformerBackwardMapper
    trainable_size: ${model.backbone.trainable_parameters.hidden2data}
    sub_graph_edge_attributes: ${model.backbone.attributes.edges}
    num_chunks: 4
    mlp_hidden_ratio: 4 # GraphTransformer or Transformer only
    num_heads: 16 # GraphTransformer or Transformer only
    initialise_data_extractor_zero: False
    qk_norm: False
    cpu_offload: ${model.backbone.cpu_offload}
    gradient_checkpointing: True
    layer_kernels: ${model.backbone.layer_kernels}
    shard_strategy: "edges"
    graph_attention_backend: "triton"  # Options: "triton", "pyg"

  residual:
    _target_: anemoi.models.layers.residual.SkipConnection # options: SkipConnection, TruncatedConnection
    step: -1 # use the latest step as skip connection
  #  _target_: anemoi.models.layers.residual.TruncatedConnection
  #  truncation_up_file_path: ${system.input.truncation}
  #  truncation_down_file_path:  ${system.input.truncation_inv}

  output_mask:
    _target_: anemoi.training.utils.masks.NoOutputMask

  trainable_parameters:
    data: 8
    hidden: 8
    data2hidden: 8
    hidden2data: 8

  attributes:
    edges:
      - edge_length
      - edge_dirs
    nodes: []

  # Bounding configuration
  bounding: #These are applied in order
    # Bound tp (total precipitation) with a Relu bounding layer
    # ensuring a range of [0, infinity) to avoid negative precipitation values.
    - _target_: anemoi.models.layers.bounding.ReluBounding #[0, infinity)
      variables:
        - tp

    # - _target_: anemoi.models.layers.bounding.FractionBounding # fraction of tp
    #   variables:
    #   - cp
    #   min_val: 0
    #   max_val: 1
    #   total_var: tp

    # - _target_: anemoi.models.layers.bounding.NormalizedReluBounding
    #   variables: [sst]
    #   min_val: [-2]
    #   normalizer: ['mean-std']

# Torch compile configuration
compile:
  - module: anemoi.models.layers.conv.GraphTransformerConv
    #options:
      #dynamic: false
      #mode: max-autotune # an example of setting the compilation mode
  - module: anemoi.models.layers.normalization.ConditionalLayerNorm
    options:
      dynamic: false
