# Configuration for standard checkpoint loading (full Lightning checkpoint)

source: null  # Path to checkpoint file (local path, S3, HTTP, etc.)
loader_type: "standard"
strict: true  # Require exact parameter matching
