datasets:
  data:
    _target_: anemoi.training.losses.combined.CombinedLoss
    scalers: ['pressure_level', 'general_variable', 'node_weights', 'time_steps']
    ignore_nans: False
    losses:
      - _target_: anemoi.training.losses.MSELoss
        scalers: ['*']
        ignore_nans: False
      - _target_: anemoi.training.losses.aggregate.TimeAggregateLossWrapper
        time_aggregation_types: [mean, max, min, diff]
        loss_fn:
          _target_: anemoi.training.losses.MSELoss
          scalers: ['pressure_level', 'general_variable', 'node_weights']
          ignore_nans: False
