---
defaults:
  - transport
  - _self_

transport_objective: stochastic_interpolant

training_loss:
  datasets:
    data:
      _target_: anemoi.training.losses.MSELoss
      scalers: ['pressure_level', 'general_variable', 'node_weights', 'time_steps']
      ignore_nans: False
