nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
      dataset:
        grids: ...
    attributes:
      cutout_mask:
        _target_: anemoi.graphs.nodes.attributes.GridsMask
  hidden: ...
