---
overwrite: True

data: "regional"
hidden: "hidden"

nodes:
  # Data nodes
  regional:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes # options: AnemoiDatasetNodes, NPZFileNodes
      dataset: ${data.sources.regional.dataset}
    attributes: ${graph.attributes.nodes}
  global:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes # options: AnemoiDatasetNodes, NPZFileNodes
      dataset: ${data.sources.global.dataset}
  # Hidden nodes
  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.TriNodes # options: AnemoiDatasetNodes, NPZFileNodes, TriNodes
      resolution: 5 # grid resolution for npz (o32, o48, ...)

edges:
# Encoder configuration
- source_name: "global"
  target_name: ${graph.hidden}
  edge_builders:
  - _target_: anemoi.graphs.edges.CutOffEdges # options: KNNEdges, CutOffEdges
    cutoff_factor: 0.6 # only for cutoff method
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes: ${graph.attributes.edges}
# Encoder configuration
- source_name: "regional"
  target_name: ${graph.hidden}
  edge_builders:
  - _target_: anemoi.graphs.edges.CutOffEdges # options: KNNEdges, CutOffEdges
    cutoff_factor: 0.6 # only for cutoff method
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes: ${graph.attributes.edges}
  # Processor configuration
- source_name: ${graph.hidden}
  target_name: ${graph.hidden}
  edge_builders:
  - _target_: anemoi.graphs.edges.MultiScaleEdges
    x_hops: 1
    scale_resolutions: ${graph.nodes.hidden.node_builder.resolution}
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes: ${graph.attributes.edges}
  # Decoder configuration
- source_name: ${graph.hidden}
  target_name: "regional"
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges # options: KNNEdges, CutOffEdges
    num_nearest_neighbours: 3 # only for knn method
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes: ${graph.attributes.edges}


attributes:
  nodes:
    area_weight:
      _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights # options: Area, Uniform
      norm: unit-max # options: l1, l2, unit-max, unit-sum, unit-std
      fill_value: 0
  edges:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-std
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

post_processors: []
