name: nightly-ci-integration-tests

on:
  schedule:
    - cron: "0 23 * * *"  # every day at 22pm on default(main) branch
  workflow_dispatch:
  push:
    branches:
      - main
      - test/initial-integration-tests

jobs:
  integration_tests:
    uses: ecmwf/reusable-workflows/nightly-pytest@add-integration-test-anemoi-move-action
    with:
      python-version: '3.10'
      install-package: "-e ./training[all,tests] -e ./graphs[all,tests] -e ./models[all,tests]"
      test-directory: "training/tests/integration"
      pytest-options: "--longtests"
      manual: ${{github.event_name == 'workflow_dispatch' && 'true' || 'false'}}
