name: nightly-ci-integration-tests

on:
  schedule:
    - cron: "0 22 * * *"  # every day at 22pm on default branch
  workflow_dispatch:


jobs:
  integration_tests:
    runs-on: [self-hosted, gpu]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: develop

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -e ./anemoi-training
        pip install -e ./anemoi-models
        pip install -e ./anemoi-graphs

    - name: Run integration tests
      run: |
        pytest tests/
