name: nightly-ci-integration-tests

on:
  schedule:
    - cron: "0 22 * * *"  # every day at 22pm on default branch
  workflow_dispatch:
  push:
    branches:
      - main
      - test/initial-integration-tests

jobs:
  integration_tests:
    uses: ecmwf-actions/reusable-workflows/.github/workflows/integration-tests.yml@add-integration-test-anemoi
    with:
      python-version: '3.10'
      install-package: "-e ./training[all,tests] -e ./graphs[all,tests] -e ./models[all,tests]"
