name: nightly-ci-integration-tests

on:
  schedule:
    - cron: "0 23 * * *"  # every day at 22pm on default branch
  workflow_dispatch:
  push:
    branches:
      - main
      - test/initial-integration-tests

jobs:
  integration_tests:
    uses: ecmwf/reusable-workflows/.github/workflows/integration-tests.yml@add-integration-test-anemoi
    with:
      python-version: '3.10'
      install-package: "-e ./training[all,tests] -e ./graphs[all,tests] -e ./models[all,tests]"
      test-directory: "training/tests/integration"
      pytest-options: "--longtests"
