name: nightly-ci-integration-tests
on:
  schedule:
    - cron: "0 23 * * *"  # every day at 22pm on default(main) branch
  workflow_dispatch:

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ecmwf/reusable-workflows/nightly-pytest
        with:
          repository: ${{github.repository}}
          ref: ${{github.ref}}
          python-version: '3.10'
          install-package: "-e ./training[all,tests] -e ./graphs[all,tests] -e ./models[all,tests]"
          test-directory: "training/tests/integration"
          pytest-options: "--longtests"
          manual: ${{github.event_name == 'workflow_dispatch' && 'true' || 'false'}}
