# This workflow checks that the appropriate ATS labels are applied to a pull request:
# - "ATS Approval Not Needed": pass
# - "ATS Approved": pass
# - "ATS Approval Needed": fail
# - Missing ATS label: fail

name: "[PR] ATS labels"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

permissions:
  pull-requests: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR labels
        uses: actions/github-script@v7
        id: check-labels
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const labels = pr.data.labels.map(label => label.name);
            core.setOutput('labels', JSON.stringify(labels));

      - name: Evaluate ATS labels
        run: |
          LABELS=$(echo '${{ steps.check-labels.outputs.labels }}' | jq -r '.[]')
          echo "Labels found:"
          echo "$LABELS"
          if echo "$LABELS" | grep -qi "ATS approval not needed"; then
            echo "ATS approval not needed. Passing."
            exit 0
          elif echo "$LABELS" | grep -qi "ATS approved"; then
            echo "ATS Approved. Passing."
            exit 0
          elif echo "$LABELS" | grep -qi "ATS approval needed"; then
              echo "ATS Approval Needed. Failing."
              exit 1
          else
            echo "No ATS approval labels found. Failing."
            exit 1
          fi
